# Name your workflow.
name: Deploy Documentation
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      # Must be set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-12
    steps:

      - name: Select Xcode 14.1
        run: sudo xcode-select -s /Applications/Xcode_14.1.app

      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs-out

      - name: Build Documentation
        run: |
          xcodebuild docbuild -scheme Puddles \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/Puddles.doccarchive \
            --hosting-base-path Puddles \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/puddles\"</script>" > docs/index.html;

      - name: Fix permissions
        run: 'sudo chown -R $USER docs-out'

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true
