# Name your workflow.
name: Deploy Documentation
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: macos-12
    steps:

      - name: Select Xcode 14.1
        run: sudo xcode-select -s /Applications/Xcode_14.1.app

      - name: Checkout Package
        uses: actions/checkout@v2

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs-out

      - name: Build documentation
        run: >
          rm -rf docs-out/.git;
          rm -rf docs-out/main;
          rm -rf "docs-out";
          
          git checkout .;
        
          swift package \
            --allow-writing-to-directory docs-out \
            generate-documentation \
            --target Puddles \
            --output-path docs-out \
            --transform-for-static-hosting \
            --hosting-base-path /Puddles;

      - name: Fix permissions
        run: 'sudo chown -R $USER docs-out'

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true
